apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::037401690852:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1654RCVJFX487
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::037401690852:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-27T13:40:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "6281"
  uid: bc27839b-458d-46e8-b9dc-c80aba0ebaee
